server:
  port: "8080"
  host: "0.0.0.0"
  mode: "debug"  # debug, release, test


database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password123"
  dbname: "myapp4454"

jwt:
  secret: "your-secret-key-change-in-production"
  expire: "24h"